### ISSUE TITLE
how to connect Amadeus services to my website?

### ISSUE THREAD

**Issue by Zee65** [amadeus4dev/data-collection#1]
how to connect Amadeus services to my website?

**Comment by anthonyroux** [comment]
Hi, you can take a look at our [Get Started](https://developers.amadeus.com/get-started/category?id=80&durl=335&parentId=NaN) that will explain to you how to create your account, how to get your API key and to do your first API call. 

You can then take a look at the catalog to choose which API is interesting for you.
Depending of your programming language, you can use on the SDK we provide in our GitHub repository.
