### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Traveeee** [amadeus4dev/data-collection#2]
@anthonyroux Hello Anthony, The hotel search API responds with only 1 image per hotel, is it normal? and how should we get rooms and other images for each hotel? if we added (view=FULL) would it work? + I'm getting an issue sometimes (server long respond) when calling API to my website

**Comment by anthonyroux** [comment]
Hey @Traveeee you can find the answer to this question here: https://stackoverflow.com/questions/60167395/how-to-get-all-images-for-a-given-hotel-using-self-service-amadeus-api

**Comment by Traveeee** [comment]
@anthonyroux Thanks for answering anthony, Can I know the reason of empty hotel search results? when I try to open hotel information I get empty results, it's happening with a lot of hotels.
